trigger:
  - main  # Запускати пайплайн при кожному коміті у гілці main


jobs:
  - job: Build_and_Test
    displayName: 'Build and Test'
    steps:
      - script: echo 'Building the project...'
        displayName: 'Build'

      - script: echo 'Running tests...'
        displayName: 'Test'
