name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v*

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag tiktak:latest
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker tag tiktak:latest ${{ github.repository_owner }}/tiktak:latest
          docker tag tiktak:latest ${{ github.repository_owner }}/tiktak:$COMMIT_HASH

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image to registry
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:latest
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:$COMMIT_HASH

      - name: Restart Azure Container Instance
        uses: azure/azure-cli@v1
        with:
          inlineScript: |
            az container restart --name tiktaktoe --resource-group Temp
