name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:latest
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:$COMMIT_HASH
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiktak:$COMMIT_HASH

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Azure Container Instance
        run: |  
          az container restart --name tiktaktoe --resource-group Temp