name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag my-image-name:latest
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker tag my-image-name:latest my-image-name:$COMMIT_HASH
