name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag tiktak:latest
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker tag tiktak:latest my-registry-url/tiktak:latest
          docker tag tiktak:$COMMIT_HASH my-registry-url/tiktak:$COMMIT_HASH
